# Generated by Django 3.0.8 on 2020-07-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200703_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityperiod',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False),
        ),
    ]
